version: '3.8'

services:
    hacker_news_service:
        restart: always
        build: ./hacker-news-service
        ports: 
            - "8000:8000"
        command: gunicorn -w 1 -b 0.0.0.0:8000 src.wsgi:app

    nginx:
        container_name: nginx  #Do not use when in a swarm; cannot scale a service beyond 1 container if you have specified a custom name
        restart: always
        build: ./nginx
        ports: 
            - "80:80"
        depends_on: 
            - hacker_news_service
